Editor/ImGui/Implementation/ImGui_RHI.h
Runtime/RHI/D3D11/D3D11_RasterizerState.cpp
Runtime/RHI/RHI_RasterizerState.h
Runtime/Rendering/Renderer.cpp
Runtime/Rendering/Renderer.h
Runtime/Rendering/Renderer_Passes.cpp

Hello. I ordinarily use my own repository. so misunderstood how to push other repository.
I thought that I push perfectly to your repository..😂😂
**The Main Body**
When using original Z, It occurs odd cascade shadow. I found out a solution after several attempts. 
This is because the front face was recognized as the rear face and was drawn as the opposite.
**Solution**
1. add other rasterizer_state that front counter clock wise is true.
2. When rendering light depth texture, if Z is original, set rasterizer state m_cull_back_ccw_solid, not m_cull_back_solid.
That's it. It took me hours to find a solution, but it's simple. that makes me sad.
[Problem]
[Fixed]
P.S I'm learning a lot from your wonderful work. Thank you!

Fixed problem that looks like speckled cascades shadow when using original Z.

---

Runtime/Rendering/Renderer_Passes.cpp

Resolves #57 
Editor seems to be fine after the change.

Fixed Startup Crash: No Camera found.

---

Runtime/Rendering/Renderer_Passes.cpp
Runtime/World/World.cpp
Runtime/World/World.h

Resolves #59 
- Fixed Crash when removing a camera and there is a light source.
- Create Default entities when creating a new World.
https://user-images.githubusercontent.com/12410116/168483270-2da93783-2ca2-4c5f-86ae-0f5766ec25a5.mp4

Fixed New World and Camera Removal when there is a Light source.

---

Runtime/Rendering/Renderer_Passes.cpp

This is a follow up PR to #60 
In this PR we add an early return if there is no camera before starting the Render Pass for the lights so we avoid iterating over every light entity. it also makes the code much cleaner and the end result is the same.
Sorry, I realized this after uploading the other PR.

Added early return if no camera is found

---

Editor/Editor.cpp
Editor/Widgets/CameraBookmarkViewer.cpp
Editor/Widgets/CameraBookmarkViewer.h
Runtime/World/Components/Camera.cpp
Runtime/World/Components/Camera.h
Runtime/World/World.h

This is a simple proof of concept for Camera Bookmarks.
Camera Bookmarks allows the user to easily navigate the world by allowing to save camera positions and then lerp between them as desired. 
- When the "Add Bookmark" button is pressed the system stores the current position and rotation of the camera.
- When the "Go To Bookmark" button is pressed the system lerps the camera to the corresponding bookmark position.
https://user-images.githubusercontent.com/12410116/168583493-749db07e-6ebe-41f0-b06b-c4a66ddd79be.mp4
- Currently the bookmarks are being loaded and unloaded at runtime, might be worth considering serialize them into a separate file for each world (or inside the .world file) in order to make them persist between sessions and having a different set of bookmarks for each World. …

[WIP] Camera Bookmarks

---

Editor/WidgetsDeferred/ButtonColorPicker.cpp
Editor/WidgetsDeferred/IconProvider.cpp
Runtime/Profiling/TimeBlock.h
Runtime/RHI/RHI_PipelineState.cpp
Runtime/World/Components/SoftBody.h
Runtime/World/Components/Terrain.cpp

All '\\' instances has been replaced by '/' in order to make the project a bit more portable (#66)

Removed all backslashes

---

Runtime/Core/SpartanDefinitions.h

PR to get closer to a working linux port (issue #66)
Removed compiler specific directives like `__debugbreak()` and `__declspec` in order to be more portable. Other systems like GNU/Linux don't support those intrinsics, so they need to be replaced.
Checking if `__GNUC__` is defined we can detect if gcc is being used
Status of PR:
GCC and CLANG seem to work differently as to what MSVC does, as they mostly work by pushing the current state, changing the state for a brief period, and then changing it back to what it was. This should not be a problem as I've seen the pattern `DISABLE_WHATEVER` do things `ENABLE_WHATEVER` in the engine, but is something to think about in the future.

Removed compiler specific directives

---

Editor/main.cpp
Runtime/Display/Display.cpp

All instances of including `Windows.h` has been removed on non-windows systems.
Older MSVC versions let you use the traditional `main(int argc, char** argv)` signature, but newer versions dont. So to solve this `ifdef` has been used in order to use one or the other signature. 
Windows functions where used on the display module in order to get the display width and heigh. The windows specific functions has been replaced with SDL functions.
A small caveat: GetWidth and GetVirtualWidth return the same value as SDL does not separate Virtual and non Virtual resolutions. A small solution would be to use Windows functions on windows while using SDL as a fallback on non supported systems. As far as I know wayland (the windowing system used on some linux systems) does not allow applications to …

Removing Windows.h

---

runtime/Math/Quaternion.cpp
runtime/World/Components/Camera.cpp
runtime/World/Components/Camera.h

- Fixed the rotation interpolation when pressing the "F" key in the viewport, with an object selected.
- Fixed the position interpolation for objects that are displaced in the scene.
- Slightly modified the way the interpolation duration is calculated.

Fix camera focus (F key) functionality

---

build_scripts/premake.lua
runtime/Core/Window.cpp
third_party/dxc/WinAdapter.h
third_party/sdl/SDL_config.h

With this PR the runtime of the game engine gets compiled in linux.
The most important change is the "modification" of the SDL library configuration. IMO this is a hint on that the approach of including the library and headers falls apart when trying to port the engine into different platforms.
#66

Compile runtime on linux

---

build_scripts/premake.lua
runtime/Core/FileSystem.h

Some minor changes in order to compile the editor in linux. 
The main problem was that the windows resource file (`resource.rc`) can't be created on linux by using the `windres` command. As far as I know the resource file holds the files like the logo and embeds it into the executable. That really does not work on linux so I decided to entirely remove it from the linux build.
#66

Compile editor on linux

---

build_scripts/Dockerfile

Add missing premake5 binary to the container to be able to prepare the build from inside the container.

Add premake5 to docker environment

---

build_scripts/Dockerfile
build_scripts/patches/freeimage.patch

This PR add serveral improvements into the build environment:
- Fixes the missing patches for building *FreeImage*
- Improves build times by using multiple jobs in make
With this PR the environment should be up and ready to work in as before. (Even better than before due to speedups!)
This PR advances on the #66 issue.

Linux: advancements in the build environment

---

data/shaders/shadow_mapping.hlsl

This PR eliminates the constant used in the compute calculation of the world position with normal offset. Its presence was causing significant seams and lighting problems in shadow-mapping. I would appreciate it if you could clarify whether this constant is essential or if its inclusion was an oversight. Based on my tests, its absence does not appear to contribute to any shadow acne issues.

Shadow bias seam

---

.editorconfig
.github/workflows/workflow.yml

Also added `.editorconfig` rule for YAML to ensure 2 spaces, it's indention dependent like Python and tends to break with tabs/4 spaces.

ignore unrelated files and folders from triggering unecessary builds

---

build_scripts/Dockerfile
build_scripts/generate_project_files.py

This PR further advances the build environment used for building the spartan engine for linux. This PR does the next things:
- Fixes the installation of FreeImage inside the environment.
- Adds OpenImageDenoise to the build environment
- Adds the `7za` binary for use in the project generation
- Optimizes builds by not downloading windows libraries
- Fixes wrong checks when the project generation is finished
This PR further advances on the #66 issue.

Further improvements on the build environment

---

runtime/Resource/IResource.h

This patch fixes a compilation error happening on Linux (that should happen also on windows to be honest) by simply adding the `Unknown` value to the `ResourceType` enumeration.
This is really strange so I might be missing something.

Fix ResourceType enum

---

build_scripts/premake.lua
generate_gmake2_vulkan.py
generate_vs2022_vulkan.py
runtime/RHI/Vulkan/Vulkan_FidelityFX.cpp
runtime/Rendering/Renderer_Passes.cpp
runtime/Rendering/Renderer_Resources.cpp

This PR removes support from linux builds for now. The SDK is not currently available officially for linux so its better to remove the dependency for now.
Status:

Remove FidelityFX from linux build

---

runtime/Core/ThreadPool.cpp
runtime/Logging/Log.cpp
runtime/Logging/Log.h
runtime/Math/Helper.h
runtime/Math/Matrix.h
runtime/Math/Vector3.h
runtime/RHI/RHI_Shader.h
runtime/RHI/RHI_Texture.cpp
runtime/RHI/Vulkan/Vulkan_FidelityFX.cpp
runtime/RHI/Vulkan/Vulkan_SwapChain.cpp
runtime/Rendering/Renderer_Passes.cpp
runtime/Rendering/Renderer_Resources.cpp
runtime/Resource/IResource.h
runtime/Resource/ResourceCache.h

Some more changes i did while compiling on linux.
It is not ready to be merged but i do not want to delay merging staff because then i never finish them, so i prepared the commits and i will also add some more for these two remaining issues i 'll include later today:

More fixes

---

build_scripts/premake.lua

The original premake script had both tabs and spaces. We should keep consistent, and since majority is spaces, I changed the indentation to spaces. There were also some other formatting nitpicks like some lines not being in the correct indentation, and braces on new lines being inconsistent.

Reformat premake script
